services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "44313:44313"
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:44313
    volumes:
      - ./local.db:/app/local.db
    restart: always
